 dist: bionic

 language: scala

 cache:
   directories:
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/

 jdk: openjdk8
 scala: "2.13.0"

 script:
   - sbt clean coverage test coverageReport coverageAggregate
   - find $HOME/.sbt -name "*.lock" | xargs rm

 after_success: "sbt coveralls"
